package org.girlscouts.vtk.auth.permission;

public enum PermissionType {

	PERMISSION_LOGIN_ID, PERMISSION_VIEW_YEARPLAN_ID,
	PERMISSION_EDIT_ACTIVITY_ID, PERMISSION_RM_ACTIVITY_ID, PERMISSION_ADD_ACTIVITY_ID,
	PERMISSION_VIEW_MEETING_ID, PERMISSION_TERMINATE_ID;

}
